name: Deploy to VM

on:
  push:
    branches: 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: build
        run: |
          npm run build

      - name: zip build
        run: tar -cvf build.tar build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}

      - name: Send zip to VM
        run: scp build.tar production:build.tar

      - name: Move build
        run: ssh production "sudo mv build.tar ../../opt/tubbdoose"

      - name: Unzip build
        run: ssh production "sudo tar -xf /opt/tubbdoose/build.tar -C /opt/tubbdoose/posts"

      - name: Remove build zip
        run: ssh production "sudo rm /opt/tubbdoose/build.tar"

      - name: Reload Nginx container
        run: ssh production "sudo docker compose  -f /opt/docker-compose.yml up -d --force-recreate nginx"